/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { Info, JobPosts } from "../models";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type DashboardOverridesProps = {
    "2"?: PrimitiveOverrideProps<TextProps>;
    "10"?: PrimitiveOverrideProps<TextProps>;
    "24"?: PrimitiveOverrideProps<TextProps>;
    "25"?: PrimitiveOverrideProps<TextProps>;
    "26"?: PrimitiveOverrideProps<TextProps>;
    "27"?: PrimitiveOverrideProps<TextProps>;
    "28"?: PrimitiveOverrideProps<TextProps>;
    "29"?: PrimitiveOverrideProps<TextProps>;
    "30"?: PrimitiveOverrideProps<TextProps>;
    Dashboard?: PrimitiveOverrideProps<ViewProps>;
    List164454?: PrimitiveOverrideProps<FlexProps>;
    "AI Generated Report"?: PrimitiveOverrideProps<TextProps>;
    List164421?: PrimitiveOverrideProps<FlexProps>;
    "Top Employee Matches"?: PrimitiveOverrideProps<TextProps>;
    People?: PrimitiveOverrideProps<FlexProps>;
    Conversation164424?: PrimitiveOverrideProps<FlexProps>;
    Avatar164425?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1164426"?: PrimitiveOverrideProps<ImageProps>;
    Text164427?: PrimitiveOverrideProps<FlexProps>;
    "Bike.Co"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net164429"?: PrimitiveOverrideProps<TextProps>;
    Conversation164430?: PrimitiveOverrideProps<FlexProps>;
    Avatar164431?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1164432"?: PrimitiveOverrideProps<ImageProps>;
    Text164433?: PrimitiveOverrideProps<FlexProps>;
    "CorporateDomains.com"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net164435"?: PrimitiveOverrideProps<TextProps>;
    Conversation164436?: PrimitiveOverrideProps<FlexProps>;
    Avatar164437?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1164438"?: PrimitiveOverrideProps<ImageProps>;
    Text164439?: PrimitiveOverrideProps<FlexProps>;
    "EarthFoods.com"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net164441"?: PrimitiveOverrideProps<TextProps>;
    Conversation164442?: PrimitiveOverrideProps<FlexProps>;
    Avatar164443?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1164444"?: PrimitiveOverrideProps<ImageProps>;
    Text164445?: PrimitiveOverrideProps<FlexProps>;
    "Winter.gov"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net164447"?: PrimitiveOverrideProps<TextProps>;
    Conversation164448?: PrimitiveOverrideProps<FlexProps>;
    Avatar164449?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1164450"?: PrimitiveOverrideProps<ImageProps>;
    Text164451?: PrimitiveOverrideProps<FlexProps>;
    "Yoshi.gov"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net164453"?: PrimitiveOverrideProps<TextProps>;
    Cards92869?: PrimitiveOverrideProps<FlexProps>;
    Cards92870?: PrimitiveOverrideProps<FlexProps>;
    Card92871?: PrimitiveOverrideProps<FlexProps>;
    "Interview Requests"?: PrimitiveOverrideProps<TextProps>;
    "Companies interested in you"?: PrimitiveOverrideProps<TextProps>;
    Card92875?: PrimitiveOverrideProps<FlexProps>;
    "Top Matches"?: PrimitiveOverrideProps<TextProps>;
    "2,405"?: PrimitiveOverrideProps<TextProps>;
    "Your top matches"?: PrimitiveOverrideProps<TextProps>;
    Card92879?: PrimitiveOverrideProps<FlexProps>;
    "Partial Matches"?: PrimitiveOverrideProps<TextProps>;
    "Missing over 25% of criteria"?: PrimitiveOverrideProps<TextProps>;
    List92897?: PrimitiveOverrideProps<FlexProps>;
    "My Page"?: PrimitiveOverrideProps<TextProps>;
    Explore?: PrimitiveOverrideProps<TextProps>;
    Calendar?: PrimitiveOverrideProps<TextProps>;
    "Line cart"?: PrimitiveOverrideProps<ViewProps>;
    Engagement?: PrimitiveOverrideProps<TextProps>;
    Lines92905?: PrimitiveOverrideProps<FlexProps>;
    "Vector 192906"?: PrimitiveOverrideProps<IconProps>;
    "Vector 392907"?: PrimitiveOverrideProps<IconProps>;
    "Vector 492908"?: PrimitiveOverrideProps<IconProps>;
    "Vector 592909"?: PrimitiveOverrideProps<IconProps>;
    "Vector 692910"?: PrimitiveOverrideProps<IconProps>;
    "Vector 792911"?: PrimitiveOverrideProps<IconProps>;
    "Vector 292912"?: PrimitiveOverrideProps<IconProps>;
    "X Axis92913"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 2610396"?: PrimitiveOverrideProps<ViewProps>;
    "23 Nov"?: PrimitiveOverrideProps<TextProps>;
    "Y Axis92923"?: PrimitiveOverrideProps<FlexProps>;
    "$50,00092924"?: PrimitiveOverrideProps<TextProps>;
    "$45,000"?: PrimitiveOverrideProps<TextProps>;
    "$40,00092926"?: PrimitiveOverrideProps<TextProps>;
    "$35,000"?: PrimitiveOverrideProps<TextProps>;
    "$30,00092928"?: PrimitiveOverrideProps<TextProps>;
    "$25,000"?: PrimitiveOverrideProps<TextProps>;
    Graph?: PrimitiveOverrideProps<IconProps>;
    Dot?: PrimitiveOverrideProps<IconProps>;
    Glow?: PrimitiveOverrideProps<IconProps>;
    "Bar chart"?: PrimitiveOverrideProps<ViewProps>;
    Lines92934?: PrimitiveOverrideProps<FlexProps>;
    "Vector 192935"?: PrimitiveOverrideProps<IconProps>;
    "Vector 392936"?: PrimitiveOverrideProps<IconProps>;
    "Vector 492937"?: PrimitiveOverrideProps<IconProps>;
    "Vector 592938"?: PrimitiveOverrideProps<IconProps>;
    "Vector 692939"?: PrimitiveOverrideProps<IconProps>;
    "Vector 792940"?: PrimitiveOverrideProps<IconProps>;
    "Vector 292941"?: PrimitiveOverrideProps<IconProps>;
    "X Axis92942"?: PrimitiveOverrideProps<FlexProps>;
    Jan?: PrimitiveOverrideProps<TextProps>;
    Feb?: PrimitiveOverrideProps<TextProps>;
    Mar?: PrimitiveOverrideProps<TextProps>;
    Apr?: PrimitiveOverrideProps<TextProps>;
    May?: PrimitiveOverrideProps<TextProps>;
    Jun?: PrimitiveOverrideProps<TextProps>;
    Jul?: PrimitiveOverrideProps<TextProps>;
    Aug?: PrimitiveOverrideProps<TextProps>;
    Sep?: PrimitiveOverrideProps<TextProps>;
    Oct?: PrimitiveOverrideProps<TextProps>;
    Nov?: PrimitiveOverrideProps<TextProps>;
    Dec?: PrimitiveOverrideProps<TextProps>;
    "Y Axis92955"?: PrimitiveOverrideProps<FlexProps>;
    "$80,000"?: PrimitiveOverrideProps<TextProps>;
    "$70,000"?: PrimitiveOverrideProps<TextProps>;
    "$60,000"?: PrimitiveOverrideProps<TextProps>;
    "$50,00092959"?: PrimitiveOverrideProps<TextProps>;
    "$40,00092960"?: PrimitiveOverrideProps<TextProps>;
    "$30,00092961"?: PrimitiveOverrideProps<TextProps>;
    "Bar list"?: PrimitiveOverrideProps<FlexProps>;
    Bar92963?: PrimitiveOverrideProps<ViewProps>;
    Bar92964?: PrimitiveOverrideProps<ViewProps>;
    Bar92965?: PrimitiveOverrideProps<ViewProps>;
    Bar92966?: PrimitiveOverrideProps<ViewProps>;
    Bar92967?: PrimitiveOverrideProps<ViewProps>;
    Bar92968?: PrimitiveOverrideProps<ViewProps>;
    Bar92969?: PrimitiveOverrideProps<ViewProps>;
    Bar92970?: PrimitiveOverrideProps<ViewProps>;
    Bar92971?: PrimitiveOverrideProps<ViewProps>;
    Bar92972?: PrimitiveOverrideProps<ViewProps>;
    Bar92973?: PrimitiveOverrideProps<ViewProps>;
    Bar92974?: PrimitiveOverrideProps<ViewProps>;
    "Top 10"?: PrimitiveOverrideProps<TextProps>;
    "Acquire Recruiting"?: PrimitiveOverrideProps<TextProps>;
    "Social Icons"?: PrimitiveOverrideProps<FlexProps>;
    "Buttons / Icon23453"?: PrimitiveOverrideProps<ViewProps>;
    Icon23454?: PrimitiveOverrideProps<ViewProps>;
    Icon23455?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / facebook"?: PrimitiveOverrideProps<ViewProps>;
    Vector23457?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon23458"?: PrimitiveOverrideProps<ViewProps>;
    Icon23459?: PrimitiveOverrideProps<ViewProps>;
    Icon23460?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / linkedin"?: PrimitiveOverrideProps<ViewProps>;
    Vector23462?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon23463"?: PrimitiveOverrideProps<ViewProps>;
    Icon23464?: PrimitiveOverrideProps<ViewProps>;
    Icon23465?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / youtube"?: PrimitiveOverrideProps<ViewProps>;
    Vector23467?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon23468"?: PrimitiveOverrideProps<ViewProps>;
    Icon23469?: PrimitiveOverrideProps<ViewProps>;
    Icon23470?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / instagram"?: PrimitiveOverrideProps<ViewProps>;
    Vector23472?: PrimitiveOverrideProps<IconProps>;
    Divider?: PrimitiveOverrideProps<IconProps>;
    NavBarHeader2?: PrimitiveOverrideProps<FlexProps>;
    "IMG-20240331-WA0000 1"?: PrimitiveOverrideProps<ImageProps>;
} & EscapeHatchProps;
export declare type DashboardProps = React.PropsWithChildren<Partial<ViewProps> & {
    Information?: Info;
    fullmatches?: Number;
    compname?: String;
    intrequest?: Number;
    partialmatches?: Number;
    jobpo?: JobPosts;
    barchart?: React.ReactNode;
    linecart?: React.ReactNode;
} & {
    overrides?: DashboardOverridesProps | undefined | null;
}>;
export default function Dashboard(props: DashboardProps): React.ReactElement;
