/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type EmployerMatchOverridesProps = {
    "2"?: PrimitiveOverrideProps<TextProps>;
    "10"?: PrimitiveOverrideProps<TextProps>;
    "24"?: PrimitiveOverrideProps<TextProps>;
    "25"?: PrimitiveOverrideProps<TextProps>;
    "26"?: PrimitiveOverrideProps<TextProps>;
    "27"?: PrimitiveOverrideProps<TextProps>;
    "28"?: PrimitiveOverrideProps<TextProps>;
    "29"?: PrimitiveOverrideProps<TextProps>;
    "30"?: PrimitiveOverrideProps<TextProps>;
    EmployerMatch?: PrimitiveOverrideProps<ViewProps>;
    List33164?: PrimitiveOverrideProps<FlexProps>;
    "AI Generated Report"?: PrimitiveOverrideProps<TextProps>;
    List33166?: PrimitiveOverrideProps<FlexProps>;
    "Top Employee Matches"?: PrimitiveOverrideProps<TextProps>;
    People?: PrimitiveOverrideProps<FlexProps>;
    Conversation33169?: PrimitiveOverrideProps<FlexProps>;
    Avatar33170?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 133171"?: PrimitiveOverrideProps<ImageProps>;
    Text33172?: PrimitiveOverrideProps<FlexProps>;
    "Bike.Co"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net33174"?: PrimitiveOverrideProps<TextProps>;
    Conversation33175?: PrimitiveOverrideProps<FlexProps>;
    Avatar33176?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 133177"?: PrimitiveOverrideProps<ImageProps>;
    Text33178?: PrimitiveOverrideProps<FlexProps>;
    "CorporateDomains.com"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net33180"?: PrimitiveOverrideProps<TextProps>;
    Conversation33181?: PrimitiveOverrideProps<FlexProps>;
    Avatar33182?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 133183"?: PrimitiveOverrideProps<ImageProps>;
    Text33184?: PrimitiveOverrideProps<FlexProps>;
    "EarthFoods.com"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net33186"?: PrimitiveOverrideProps<TextProps>;
    Conversation33187?: PrimitiveOverrideProps<FlexProps>;
    Avatar33188?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 133189"?: PrimitiveOverrideProps<ImageProps>;
    Text33190?: PrimitiveOverrideProps<FlexProps>;
    "Winter.gov"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net33192"?: PrimitiveOverrideProps<TextProps>;
    Conversation33193?: PrimitiveOverrideProps<FlexProps>;
    Avatar33194?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 133195"?: PrimitiveOverrideProps<ImageProps>;
    Text33196?: PrimitiveOverrideProps<FlexProps>;
    "Yoshi.gov"?: PrimitiveOverrideProps<TextProps>;
    "email@figmasfakedomain.net33198"?: PrimitiveOverrideProps<TextProps>;
    Cards33199?: PrimitiveOverrideProps<FlexProps>;
    Cards33200?: PrimitiveOverrideProps<FlexProps>;
    Card33201?: PrimitiveOverrideProps<FlexProps>;
    "Interview Requests"?: PrimitiveOverrideProps<TextProps>;
    "Companies interested in you"?: PrimitiveOverrideProps<TextProps>;
    Card33205?: PrimitiveOverrideProps<FlexProps>;
    "Top Matches"?: PrimitiveOverrideProps<TextProps>;
    "2,405"?: PrimitiveOverrideProps<TextProps>;
    "Your top matches"?: PrimitiveOverrideProps<TextProps>;
    Card33209?: PrimitiveOverrideProps<FlexProps>;
    "Partial Matches"?: PrimitiveOverrideProps<TextProps>;
    "Missing over 25% of criteria"?: PrimitiveOverrideProps<TextProps>;
    Navigation?: PrimitiveOverrideProps<ViewProps>;
    Avatar33216?: PrimitiveOverrideProps<FlexProps>;
    Avatar33217?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 133218"?: PrimitiveOverrideProps<ImageProps>;
    "chevron-down"?: PrimitiveOverrideProps<ViewProps>;
    Vector33220?: PrimitiveOverrideProps<IconProps>;
    Buttons?: PrimitiveOverrideProps<FlexProps>;
    Button?: PrimitiveOverrideProps<FlexProps>;
    "more-horizontal"?: PrimitiveOverrideProps<ViewProps>;
    Vector33224?: PrimitiveOverrideProps<IconProps>;
    Vector33225?: PrimitiveOverrideProps<IconProps>;
    Vector33226?: PrimitiveOverrideProps<IconProps>;
    "Acquire Recruiting33231"?: PrimitiveOverrideProps<TextProps>;
    List27781079?: PrimitiveOverrideProps<FlexProps>;
    "My Page"?: PrimitiveOverrideProps<TextProps>;
    Explore?: PrimitiveOverrideProps<TextProps>;
    Calendar?: PrimitiveOverrideProps<TextProps>;
    "IMG-20240331-WA0000 1"?: PrimitiveOverrideProps<ImageProps>;
    "Line cart"?: PrimitiveOverrideProps<ViewProps>;
    Engagement?: PrimitiveOverrideProps<TextProps>;
    Lines33235?: PrimitiveOverrideProps<FlexProps>;
    "Vector 133236"?: PrimitiveOverrideProps<IconProps>;
    "Vector 333237"?: PrimitiveOverrideProps<IconProps>;
    "Vector 433238"?: PrimitiveOverrideProps<IconProps>;
    "Vector 533239"?: PrimitiveOverrideProps<IconProps>;
    "Vector 633240"?: PrimitiveOverrideProps<IconProps>;
    "Vector 733241"?: PrimitiveOverrideProps<IconProps>;
    "Vector 233242"?: PrimitiveOverrideProps<IconProps>;
    "X Axis33243"?: PrimitiveOverrideProps<FlexProps>;
    "Frame 2610396"?: PrimitiveOverrideProps<ViewProps>;
    "23 Nov"?: PrimitiveOverrideProps<TextProps>;
    "Y Axis33253"?: PrimitiveOverrideProps<FlexProps>;
    "$50,00033254"?: PrimitiveOverrideProps<TextProps>;
    "$45,000"?: PrimitiveOverrideProps<TextProps>;
    "$40,00033256"?: PrimitiveOverrideProps<TextProps>;
    "$35,000"?: PrimitiveOverrideProps<TextProps>;
    "$30,00033258"?: PrimitiveOverrideProps<TextProps>;
    "$25,000"?: PrimitiveOverrideProps<TextProps>;
    Graph?: PrimitiveOverrideProps<IconProps>;
    Dot?: PrimitiveOverrideProps<IconProps>;
    Glow?: PrimitiveOverrideProps<IconProps>;
    "Bar chart"?: PrimitiveOverrideProps<ViewProps>;
    Lines33264?: PrimitiveOverrideProps<FlexProps>;
    "Vector 133265"?: PrimitiveOverrideProps<IconProps>;
    "Vector 333266"?: PrimitiveOverrideProps<IconProps>;
    "Vector 433267"?: PrimitiveOverrideProps<IconProps>;
    "Vector 533268"?: PrimitiveOverrideProps<IconProps>;
    "Vector 633269"?: PrimitiveOverrideProps<IconProps>;
    "Vector 733270"?: PrimitiveOverrideProps<IconProps>;
    "Vector 233271"?: PrimitiveOverrideProps<IconProps>;
    "X Axis33272"?: PrimitiveOverrideProps<FlexProps>;
    Jan?: PrimitiveOverrideProps<TextProps>;
    Feb?: PrimitiveOverrideProps<TextProps>;
    Mar?: PrimitiveOverrideProps<TextProps>;
    Apr?: PrimitiveOverrideProps<TextProps>;
    May?: PrimitiveOverrideProps<TextProps>;
    Jun?: PrimitiveOverrideProps<TextProps>;
    Jul?: PrimitiveOverrideProps<TextProps>;
    Aug?: PrimitiveOverrideProps<TextProps>;
    Sep?: PrimitiveOverrideProps<TextProps>;
    Oct?: PrimitiveOverrideProps<TextProps>;
    Nov?: PrimitiveOverrideProps<TextProps>;
    Dec?: PrimitiveOverrideProps<TextProps>;
    "Y Axis33285"?: PrimitiveOverrideProps<FlexProps>;
    "$80,000"?: PrimitiveOverrideProps<TextProps>;
    "$70,000"?: PrimitiveOverrideProps<TextProps>;
    "$60,000"?: PrimitiveOverrideProps<TextProps>;
    "$50,00033289"?: PrimitiveOverrideProps<TextProps>;
    "$40,00033290"?: PrimitiveOverrideProps<TextProps>;
    "$30,00033291"?: PrimitiveOverrideProps<TextProps>;
    "Bar list"?: PrimitiveOverrideProps<FlexProps>;
    Bar33293?: PrimitiveOverrideProps<ViewProps>;
    Bar33294?: PrimitiveOverrideProps<ViewProps>;
    Bar33295?: PrimitiveOverrideProps<ViewProps>;
    Bar33296?: PrimitiveOverrideProps<ViewProps>;
    Bar33297?: PrimitiveOverrideProps<ViewProps>;
    Bar33298?: PrimitiveOverrideProps<ViewProps>;
    Bar33299?: PrimitiveOverrideProps<ViewProps>;
    Bar33300?: PrimitiveOverrideProps<ViewProps>;
    Bar33301?: PrimitiveOverrideProps<ViewProps>;
    Bar33302?: PrimitiveOverrideProps<ViewProps>;
    Bar33303?: PrimitiveOverrideProps<ViewProps>;
    Bar33304?: PrimitiveOverrideProps<ViewProps>;
    "Top 10"?: PrimitiveOverrideProps<TextProps>;
    "Acquire Recruiting33362"?: PrimitiveOverrideProps<TextProps>;
    "Social Icons"?: PrimitiveOverrideProps<FlexProps>;
    "Buttons / Icon33364"?: PrimitiveOverrideProps<ViewProps>;
    Icon33365?: PrimitiveOverrideProps<ViewProps>;
    Icon33366?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / facebook"?: PrimitiveOverrideProps<ViewProps>;
    Vector33368?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33369"?: PrimitiveOverrideProps<ViewProps>;
    Icon33370?: PrimitiveOverrideProps<ViewProps>;
    Icon33371?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / linkedin"?: PrimitiveOverrideProps<ViewProps>;
    Vector33373?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33374"?: PrimitiveOverrideProps<ViewProps>;
    Icon33375?: PrimitiveOverrideProps<ViewProps>;
    Icon33376?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / youtube"?: PrimitiveOverrideProps<ViewProps>;
    Vector33378?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33379"?: PrimitiveOverrideProps<ViewProps>;
    Icon33380?: PrimitiveOverrideProps<ViewProps>;
    Icon33381?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / instagram"?: PrimitiveOverrideProps<ViewProps>;
    Vector33383?: PrimitiveOverrideProps<IconProps>;
    Divider?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type EmployerMatchProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: EmployerMatchOverridesProps | undefined | null;
}>;
export default function EmployerMatch(props: EmployerMatchProps): React.ReactElement;
