/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type PortfolioOverridesProps = {
    Portfolio?: PrimitiveOverrideProps<ViewProps>;
    Card338?: PrimitiveOverrideProps<FlexProps>;
    "paperclip 1339"?: PrimitiveOverrideProps<ViewProps>;
    Copy3310?: PrimitiveOverrideProps<FlexProps>;
    "Professional Achievements"?: PrimitiveOverrideProps<TextProps>;
    "Fill in here3312"?: PrimitiveOverrideProps<TextProps>;
    Copy33156?: PrimitiveOverrideProps<FlexProps>;
    "Interests/Hobbies"?: PrimitiveOverrideProps<TextProps>;
    "Fill in here33158"?: PrimitiveOverrideProps<TextProps>;
    Copy3313?: PrimitiveOverrideProps<FlexProps>;
    "Work History"?: PrimitiveOverrideProps<TextProps>;
    "Fill in Here"?: PrimitiveOverrideProps<TextProps>;
    Card3319?: PrimitiveOverrideProps<FlexProps>;
    "paperclip 13320"?: PrimitiveOverrideProps<ViewProps>;
    Copy3321?: PrimitiveOverrideProps<FlexProps>;
    Education?: PrimitiveOverrideProps<TextProps>;
    "Fill in here3323"?: PrimitiveOverrideProps<TextProps>;
    Copy3324?: PrimitiveOverrideProps<FlexProps>;
    "Jane Doe"?: PrimitiveOverrideProps<TextProps>;
    "A subheading with a brief description of you, your work, and what you\u2019re all about\u2014no biggie"?: PrimitiveOverrideProps<TextProps>;
    "Professional Focus"?: PrimitiveOverrideProps<TextProps>;
    "Social Icons3328"?: PrimitiveOverrideProps<FlexProps>;
    "Buttons / Icon3329"?: PrimitiveOverrideProps<ViewProps>;
    Icon3330?: PrimitiveOverrideProps<ViewProps>;
    Icon3331?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / facebook3332"?: PrimitiveOverrideProps<ViewProps>;
    Vector3333?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon3334"?: PrimitiveOverrideProps<ViewProps>;
    Icon3335?: PrimitiveOverrideProps<ViewProps>;
    Icon3336?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / linkedin3337"?: PrimitiveOverrideProps<ViewProps>;
    Vector3338?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon3339"?: PrimitiveOverrideProps<ViewProps>;
    Icon3340?: PrimitiveOverrideProps<ViewProps>;
    Icon3341?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / youtube3342"?: PrimitiveOverrideProps<ViewProps>;
    Vector3343?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon3344"?: PrimitiveOverrideProps<ViewProps>;
    Icon3345?: PrimitiveOverrideProps<ViewProps>;
    Icon3346?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / instagram3347"?: PrimitiveOverrideProps<ViewProps>;
    Vector3348?: PrimitiveOverrideProps<IconProps>;
    "00 Primary button"?: PrimitiveOverrideProps<FlexProps>;
    "UPLOAD YOUR RESUME"?: PrimitiveOverrideProps<TextProps>;
    "Left sidebar"?: PrimitiveOverrideProps<ViewProps>;
    List3352?: PrimitiveOverrideProps<FlexProps>;
    "Menu item3353"?: PrimitiveOverrideProps<FlexProps>;
    home?: PrimitiveOverrideProps<ViewProps>;
    Vector3355?: PrimitiveOverrideProps<IconProps>;
    Vector3356?: PrimitiveOverrideProps<IconProps>;
    Home?: PrimitiveOverrideProps<TextProps>;
    "Menu item3358"?: PrimitiveOverrideProps<FlexProps>;
    search?: PrimitiveOverrideProps<ViewProps>;
    Vector3360?: PrimitiveOverrideProps<IconProps>;
    Vector3361?: PrimitiveOverrideProps<IconProps>;
    Search?: PrimitiveOverrideProps<TextProps>;
    "Menu item3363"?: PrimitiveOverrideProps<FlexProps>;
    bell?: PrimitiveOverrideProps<ViewProps>;
    Vector3365?: PrimitiveOverrideProps<IconProps>;
    Vector3366?: PrimitiveOverrideProps<IconProps>;
    Notifications?: PrimitiveOverrideProps<TextProps>;
    "Menu item3368"?: PrimitiveOverrideProps<FlexProps>;
    bookmark?: PrimitiveOverrideProps<ViewProps>;
    Vector3370?: PrimitiveOverrideProps<IconProps>;
    Activity?: PrimitiveOverrideProps<TextProps>;
    "Menu item3372"?: PrimitiveOverrideProps<FlexProps>;
    "message-circle"?: PrimitiveOverrideProps<ViewProps>;
    Vector3374?: PrimitiveOverrideProps<IconProps>;
    Messages?: PrimitiveOverrideProps<TextProps>;
    "List card"?: PrimitiveOverrideProps<FlexProps>;
    About?: PrimitiveOverrideProps<TextProps>;
    "Acquire Recruiting3378"?: PrimitiveOverrideProps<TextProps>;
    "Social Icons3379"?: PrimitiveOverrideProps<FlexProps>;
    "Buttons / Icon3380"?: PrimitiveOverrideProps<ViewProps>;
    Icon3381?: PrimitiveOverrideProps<ViewProps>;
    Icon3382?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / facebook3383"?: PrimitiveOverrideProps<ViewProps>;
    Vector3384?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon3385"?: PrimitiveOverrideProps<ViewProps>;
    Icon3386?: PrimitiveOverrideProps<ViewProps>;
    Icon3387?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / linkedin3388"?: PrimitiveOverrideProps<ViewProps>;
    Vector3389?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon3390"?: PrimitiveOverrideProps<ViewProps>;
    Icon3391?: PrimitiveOverrideProps<ViewProps>;
    Icon3392?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / youtube3393"?: PrimitiveOverrideProps<ViewProps>;
    Vector3394?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon3395"?: PrimitiveOverrideProps<ViewProps>;
    Icon3396?: PrimitiveOverrideProps<ViewProps>;
    Icon3397?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / instagram3398"?: PrimitiveOverrideProps<ViewProps>;
    Vector3399?: PrimitiveOverrideProps<IconProps>;
    Divider?: PrimitiveOverrideProps<IconProps>;
    Navigation?: PrimitiveOverrideProps<ViewProps>;
    Avatar33102?: PrimitiveOverrideProps<FlexProps>;
    Avatar33103?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1"?: PrimitiveOverrideProps<ImageProps>;
    "chevron-down"?: PrimitiveOverrideProps<ViewProps>;
    Vector33106?: PrimitiveOverrideProps<IconProps>;
    Buttons?: PrimitiveOverrideProps<FlexProps>;
    Button?: PrimitiveOverrideProps<FlexProps>;
    "more-horizontal"?: PrimitiveOverrideProps<ViewProps>;
    Vector33110?: PrimitiveOverrideProps<IconProps>;
    Vector33111?: PrimitiveOverrideProps<IconProps>;
    Vector33112?: PrimitiveOverrideProps<IconProps>;
    List33113?: PrimitiveOverrideProps<FlexProps>;
    "My Page"?: PrimitiveOverrideProps<TextProps>;
    Explore?: PrimitiveOverrideProps<TextProps>;
    Calendar?: PrimitiveOverrideProps<TextProps>;
    Chat?: PrimitiveOverrideProps<TextProps>;
    "Acquire Recruiting33118"?: PrimitiveOverrideProps<TextProps>;
    "image 1"?: PrimitiveOverrideProps<ImageProps>;
    Graphic?: PrimitiveOverrideProps<ViewProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Line 3"?: PrimitiveOverrideProps<IconProps>;
} & EscapeHatchProps;
export declare type PortfolioProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: PortfolioOverridesProps | undefined | null;
}>;
export default function Portfolio(props: PortfolioProps): React.ReactElement;
