/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

import * as React from "react";
import { FlexProps, IconProps, ImageProps, TextProps, ViewProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type PublicProfileOverridesProps = {
    PublicProfile?: PrimitiveOverrideProps<ViewProps>;
    Card33556?: PrimitiveOverrideProps<FlexProps>;
    "paperclip 133557"?: PrimitiveOverrideProps<ViewProps>;
    Copy33558?: PrimitiveOverrideProps<FlexProps>;
    "What the Company is looking for33559"?: PrimitiveOverrideProps<TextProps>;
    "Fill in here33560"?: PrimitiveOverrideProps<TextProps>;
    Copy33561?: PrimitiveOverrideProps<FlexProps>;
    "Salary Range"?: PrimitiveOverrideProps<TextProps>;
    "Fill in here33563"?: PrimitiveOverrideProps<TextProps>;
    Copy33564?: PrimitiveOverrideProps<FlexProps>;
    Benefits33565?: PrimitiveOverrideProps<TextProps>;
    "Fill in Here33566"?: PrimitiveOverrideProps<TextProps>;
    Copy33567?: PrimitiveOverrideProps<FlexProps>;
    Benefits33568?: PrimitiveOverrideProps<TextProps>;
    "Fill in Here33569"?: PrimitiveOverrideProps<TextProps>;
    Copy33570?: PrimitiveOverrideProps<FlexProps>;
    "Other Info"?: PrimitiveOverrideProps<TextProps>;
    "Fill in Here33572"?: PrimitiveOverrideProps<TextProps>;
    Card33573?: PrimitiveOverrideProps<FlexProps>;
    "paperclip 133574"?: PrimitiveOverrideProps<ViewProps>;
    Copy33575?: PrimitiveOverrideProps<FlexProps>;
    "Johnson & Johnson"?: PrimitiveOverrideProps<TextProps>;
    "A subheading with a brief description of you, your work, and what you\u2019re all about\u2014no biggie"?: PrimitiveOverrideProps<TextProps>;
    Location?: PrimitiveOverrideProps<TextProps>;
    "Social Icons33579"?: PrimitiveOverrideProps<FlexProps>;
    "Buttons / Icon33580"?: PrimitiveOverrideProps<ViewProps>;
    Icon33581?: PrimitiveOverrideProps<ViewProps>;
    Icon33582?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / facebook33583"?: PrimitiveOverrideProps<ViewProps>;
    Vector33584?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33585"?: PrimitiveOverrideProps<ViewProps>;
    Icon33586?: PrimitiveOverrideProps<ViewProps>;
    Icon33587?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / linkedin33588"?: PrimitiveOverrideProps<ViewProps>;
    Vector33589?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33590"?: PrimitiveOverrideProps<ViewProps>;
    Icon33591?: PrimitiveOverrideProps<ViewProps>;
    Icon33592?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / youtube33593"?: PrimitiveOverrideProps<ViewProps>;
    Vector33594?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33595"?: PrimitiveOverrideProps<ViewProps>;
    Icon33596?: PrimitiveOverrideProps<ViewProps>;
    Icon33597?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / instagram33598"?: PrimitiveOverrideProps<ViewProps>;
    Vector33599?: PrimitiveOverrideProps<IconProps>;
    "00 Primary button33600"?: PrimitiveOverrideProps<FlexProps>;
    "VIEW WEBSITE"?: PrimitiveOverrideProps<TextProps>;
    "List card"?: PrimitiveOverrideProps<FlexProps>;
    "Positions Available with Johnson & Johnson"?: PrimitiveOverrideProps<TextProps>;
    "What the Company is looking for33629"?: PrimitiveOverrideProps<TextProps>;
    "Acquire Recruiting33630"?: PrimitiveOverrideProps<TextProps>;
    "Social Icons33631"?: PrimitiveOverrideProps<FlexProps>;
    "Buttons / Icon33632"?: PrimitiveOverrideProps<ViewProps>;
    Icon33633?: PrimitiveOverrideProps<ViewProps>;
    Icon33634?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / facebook33635"?: PrimitiveOverrideProps<ViewProps>;
    Vector33636?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33637"?: PrimitiveOverrideProps<ViewProps>;
    Icon33638?: PrimitiveOverrideProps<ViewProps>;
    Icon33639?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / linkedin33640"?: PrimitiveOverrideProps<ViewProps>;
    Vector33641?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33642"?: PrimitiveOverrideProps<ViewProps>;
    Icon33643?: PrimitiveOverrideProps<ViewProps>;
    Icon33644?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / youtube33645"?: PrimitiveOverrideProps<ViewProps>;
    Vector33646?: PrimitiveOverrideProps<IconProps>;
    "Buttons / Icon33647"?: PrimitiveOverrideProps<ViewProps>;
    Icon33648?: PrimitiveOverrideProps<ViewProps>;
    Icon33649?: PrimitiveOverrideProps<IconProps>;
    "Icons / Social / instagram33650"?: PrimitiveOverrideProps<ViewProps>;
    Vector33651?: PrimitiveOverrideProps<IconProps>;
    Divider?: PrimitiveOverrideProps<IconProps>;
    Navigation?: PrimitiveOverrideProps<ViewProps>;
    Avatar33654?: PrimitiveOverrideProps<FlexProps>;
    Avatar33655?: PrimitiveOverrideProps<ViewProps>;
    "Rectangle 1"?: PrimitiveOverrideProps<ImageProps>;
    "chevron-down"?: PrimitiveOverrideProps<ViewProps>;
    Vector33658?: PrimitiveOverrideProps<IconProps>;
    Buttons?: PrimitiveOverrideProps<FlexProps>;
    Button?: PrimitiveOverrideProps<FlexProps>;
    "more-horizontal"?: PrimitiveOverrideProps<ViewProps>;
    Vector33662?: PrimitiveOverrideProps<IconProps>;
    Vector33663?: PrimitiveOverrideProps<IconProps>;
    Vector33664?: PrimitiveOverrideProps<IconProps>;
    List?: PrimitiveOverrideProps<FlexProps>;
    "My Page"?: PrimitiveOverrideProps<TextProps>;
    Explore?: PrimitiveOverrideProps<TextProps>;
    Calendar?: PrimitiveOverrideProps<TextProps>;
    Chat?: PrimitiveOverrideProps<TextProps>;
    "Acquire Recruiting33670"?: PrimitiveOverrideProps<TextProps>;
    "image 133671"?: PrimitiveOverrideProps<ImageProps>;
    Graphic?: PrimitiveOverrideProps<ViewProps>;
    "Line 2"?: PrimitiveOverrideProps<IconProps>;
    "Line 3"?: PrimitiveOverrideProps<IconProps>;
    "00 Primary button33708"?: PrimitiveOverrideProps<FlexProps>;
    "REQUEST INTERVIEW"?: PrimitiveOverrideProps<TextProps>;
    "image 133710"?: PrimitiveOverrideProps<ImageProps>;
} & EscapeHatchProps;
export declare type PublicProfileProps = React.PropsWithChildren<Partial<ViewProps> & {
    overrides?: PublicProfileOverridesProps | undefined | null;
}>;
export default function PublicProfile(props: PublicProfileProps): React.ReactElement;
